name: Compile C++ to WebAssembly and Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Zmień na nazwę głównej gałęzi, jeśli inna

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Emscripten
        run: |
          git clone https://github.com/emscripten-core/emsdk.git
          cd emsdk
          ./emsdk install latest
          ./emsdk activate latest
        shell: bash

      - name: Compile C++ to WebAssembly
        run: |
          source emsdk/emsdk_env.sh
          mkdir -p dist
          emcc tetris2.c \
            -s WASM=1 \
            -s USE_SDL=2 \
            -s USE_SDL_IMAGE=2 \
            -s SDL2_IMAGE_FORMATS='["png"]' \
            -s USE_SDL_TTF=2 \
            -s USE_WEBGL2=1 \
            -s MAX_WEBGL_VERSION=2 \
            -s MIN_WEBGL_VERSION=2 \
            --preload-file assets/fast99.ttf \
            -o dist/index.html
        shell: bash

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
